name: Build driver
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        image_additional_mb: 1500
        bind_mount_repository: true
        commands: |
            apt-get update
            apt-get install -y libopencv-dev libegl1-mesa-dev libcamera-dev cmake build-essential libdrm-dev libgbm-dev openjdk-11-jdk
            cmake -B build-pi -DCMAKE_BUILD_TYPE=Release
            cmake --build build-pi -j 4

    - run: find .

    # Upload client artifact.
    - uses: actions/upload-artifact@master
      with:
        name: libcamera-driver
        path: build-pi/*.so
