name: Build driver
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        image_additional_mb: 1000
        commands: |
            apt-get update
            apt-get install -y libopencv-dev libegl1-mesa-dev libcamera-dev
            cmake -B build-pi -DCMAKE_BUILD_TYPE=Release
            cmake --build build-pi -j 4
